config/routes.rb
RottenMangoes::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  namespace :admin do
    resources :users
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'

  

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  scope :Under90, ->  { where("runtime_in_minutes < ?", 90) }
  scope :Between90and120, -> { where("runtime_in_minutes > ? AND runtime_in_minutes < ?", 90, 120) } 
  scope :Over120, -> { where("runtime_in_minutes > ?", 120) } 

  has_many :reviews

  mount_uploader :poster, PosterUploader

  validates :title,
  presence: true

  validates :director,
  presence: true

  validates :runtime_in_minutes,
  numericality: { only_integer: true }

  validates :description,
  presence: true

  # validates :poster_image_url,
  # presence: true

  validates :poster,
  presence: true

  validates :release_date,
  presence: true

  validate :release_date_is_in_the_past


  def review_average
    reviews.sum(:rating_out_of_ten)/reviews.size
  end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      erros.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie    

  validates :user,
  presence: true

  validates :movie,
  presence: true

  validates :text,
  presence: true

  validates :rating_out_of_ten,
  numericality: { only_integer: true }

  validates :rating_out_of_ten,
  numericality: { greater_than_or_equal_to: 1 }
  
  validates :rating_out_of_ten,
  numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews
  has_secure_password
  paginates_per 10

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :require_admin
  helper_method :paginate
  # Methods omitted

  def require_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end

  def index
    @users = User.order(:lastname).page params[:page]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def edit
    if params[:admin]
      @user = User.find(params[:id])
      @user.admin = params[:admin]
    else
      @user = User.find(params[:id])
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.welcome_email(@user).deliver
    @user.destroy
    redirect_to admin_user_path
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

  def paginate

  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    @movie = Movie.new

    @movies = Movie.where("title LIKE ?", "%#{params[:title]}%")
                   .where("director LIKE ?", "%#{params[:director]}%")

    case params[:runtime_in_minutes]
    
    when "Under90"
      @movies = @movies.Under90
    when "90 to 120"
      @movies = @movies.Between90and120
    when "Over120"
      @movies = @movies.Over120
    else
      @movies 
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
    :title, :release_date, :director, :runtime_in_minutes, :poster, :description
    )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/session_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @users = User.all
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<h1>Sign Up</h1>
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :admin %><br>
    <%= select_tag :admin, options_for_select([['Yes', true], ["No", false]]) %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= render 'form' %>

app/views/admin/users/index.html.erb
<%= link_to "Create a User", new_admin_user_path %>

<% @users.each do |user| %>
  <p><%= link_to user.firstname, admin_user_path(user) %> | <%= user.lastname %> | <%= user.email %></p>
<% end %>

app/views/admin/users/new.html.erb
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h2>(<%= link_to "edit", edit_admin_user_path(@user) %>, <%= link_to "delete", admin_user_path(@user), method: :delete, confirm: "You sure?" %>)</h2>
<h3><%= @user.firstname %> | <%= @user.lastname %></h3>
<h4> <%= @user.email %></h4>
<hr>

app/views/layouts/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="..." alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="..." alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_footer.html.erb
 <footer>
  <div id="footer">
    <div class="navbar-inverse navbarcustom" role="navigation">
      <div class="container">
        <div class="navbar-text pull-left">
          <p id="footertext">©2016 Rotten Mangoes.</p>
        </div>
        <div class="navbar-text pull-right">
          <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
          <a href="#"><i class="fa fa-twitter fa-2x"></i></a>
          <a href="#"><i class="fa fa-google-plus fa-2x"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div id="bar">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul>
        <p class="active navbar-brand" href="#"><%= link_to "Rotten Mangoes", movies_path %></p>
      </ul>
    </div>
    <div id="mainnavbar" class="navbar-collapse collapse">
      <div class="nav navbar-nav navbar-left">
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle btn btn-info" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Search<span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><a href="#"><%= render 'movies/search' %></a></li>
          </ul>
        </div>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="#popular_now">Popular Now</a></li>
        <li class="active"><a href="#my_list">My List</a></li>
        <li class="active"><a href="#coming_soon">Coming Soon</a></li>
        <% if current_user %>
          <li class="active"><a class="btn btn-primary">  Signed in as <%= current_user.full_name %> </a></li>
          <li class="active "><a><%= link_to "Log out", session_path("current"), method: :delete %></a></li>
        <% else %>
          <li class="active"><%= link_to "Log In", new_session_path %></li>  
          <li class="active"><%= link_to "Sign Up", new_user_path %></li> 
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="images/mango.png" type="image/x-icon">
    <link rel="stylesheet" href="/stylesheets/normalize.css">
    <link rel="stylesheet" href="/stylesheets/bootstrap.css">
    <link rel="stylesheet" href="/stylesheets/animate.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity=" sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="/stylesheets/application.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="/javascript/application.js"></script>
    <script src="/javascript/bootstrap.js"></script>
    <title>RottenMangoes</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="page-wrap">
      <%= render 'layouts/navbar' %>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value) %>
      <% end %>
      <div class="space"></div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
      <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div>
    <%= f.label :poster %><br>
    <%= f.file_field :poster %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<h1 id="list">My List</h1>
<button id="submitbutton" class="btn btn-success"><%= link_to "Submit Something", new_movie_path %></button></br>
<% @movies.each do |movie| %>
  <div class="col-lg-1">
    <div class="moviepagepic"><%= link_to image_tag(movie.poster), movie_path(movie) %></div>
<!--       <h2><%= link_to movie.title, movie_path(movie) %></h2> -->
    </div>
<% end %>
   
 

app/views/movies/_search.html.erb
<div class="searchbar">
  <h1>Looking For Something?</h1>
  <%= form_tag movies_path, method: :get, class: "search_form", id: "foo" do %>
    <p><%= text_field_tag :title, nil, placeholder: "Title" %></p>
    <p><%= text_field_tag :director, nil, placeholder: "Director" %></p>
    <p><%= select_tag :runtime_in_minutes, options_for_select([["Pick a Runtime"], ['Less than 90 minutes', "Under90"], ["90 to 120 minutes", "90 to 120"], ["Over 120 minutes", "Over120"]]) %></p>
    <a class="btn btn-default"><%= submit_tag "Search" %></a>
  <% end %>
</div>

app/views/movies/index.html.erb
<div class="topbar">
  <h1 id="welcome">Welcome To Rotten Mangoes</h1>
  <div class="row">
    <div class="col-md-4">
      <h1>Movies</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in placerat dolor. Suspendisse quis congue lacus, tempor euismod enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam ut velit non lacus blandit ullamcorper nec ac eros. Praesent vulputate sollicitudin lectus, sed pellentesque ipsum laoreet nec. Sed malesuada rhoncus tempus. Aliquam eget magna quis nulla pretium sagittis. Fusce rhoncus porta tellus, a interdum odio ullamcorper condimentum. Duis sit amet felis odio. Nam dictum nunc orci, sed dapibus arcu venenatis et.</p>
    </div>
    <div class="col-md-4">
      <h1>TV Shows</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in placerat dolor. Suspendisse quis congue lacus, tempor euismod enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam ut velit non lacus blandit ullamcorper nec ac eros. Praesent vulputate sollicitudin lectus, sed pellentesque ipsum laoreet nec. Sed malesuada rhoncus tempus. Aliquam eget magna quis nulla pretium sagittis. Fusce rhoncus porta tellus, a interdum odio ullamcorper condimentum. Duis sit amet felis odio. Nam dictum nunc orci, sed dapibus arcu venenatis et.</p>
    </div>
    <div class="col-lg-4">
      <h1>Anime</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in placerat dolor. Suspendisse quis congue lacus, tempor euismod enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam ut velit non lacus blandit ullamcorper nec ac eros. Praesent vulputate sollicitudin lectus, sed pellentesque ipsum laoreet nec. Sed malesuada rhoncus tempus. Aliquam eget magna quis nulla pretium sagittis. Fusce rhoncus porta tellus, a interdum odio ullamcorper condimentum. Duis sit amet felis odio. Nam dictum nunc orci, sed dapibus arcu venenatis et.</p>
    </div>
  </div>
</div>
<h1 id = "popular_now" class="popular">Popular Now</h1>
<section class="module parallax parallax-1"></section>
<div class="container">
  <div id="my_list" class="row">
    <%= render "movie" %>
  </div>
</div>
<h1 id="coming_soon" class="popular">Coming Soon</h1>
<section class="module parallax parallax-2"></section>
<div class="indexspace"></div>

app/views/movies/new.html.erb
<%= render 'form' %>
<div class="bottom"></div>

app/views/movies/show.html.erb
<div id ="showpage"class="container">
  <br/>
  <%= link_to image_tag(@movie.poster), movie_path(@movie) %>
  <h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
  <h3><%= @movie.release_date.to_date %></h3>
  <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
  <p><%= @movie.description %></p>
  <hr>
  <h3>Reviews of <em><%= @movie.title %></em></h3>
  <% if current_user %>
    <% @movie.reviews.each do |review| %>
      <p><%= review.text %></p>
      <p><%= review.rating_out_of_ten %>/10</p>
      <small>- <%= review.user.full_name %></small><br/>
    <% end %>
    <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
  <% else %>
    <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
  <% end %>
</div>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>
<h2>Write a review of <em><%= @movie.title %></em>.</h2>
<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :text %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="bottom">
    <%= f.submit "Submit" %>
  </div>
<% end %>